default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: 11_development1

test:
  <<: *default
  database: 11_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
    database: myapp_production
    pool: 5
    username: myuser
    password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
    host: localhost

  cable:
    adapter: postgresql
    encoding: unicode
    database: myapp_production
    pool: 5
    username: myuser
    password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
    host: localhost

  <<: *default
  database: avoblog_production
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'postgres' %>